// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Episode struct {
	ID          string  `json:"id"`
	EpisodeNo   *int    `json:"episodeNo,omitempty"`
	Description *string `json:"description,omitempty"`
}

type EpisodeInput struct {
	EpisodeNumber int    `json:"episodeNumber"`
	EpisodeName   string `json:"episodeName"`
}

type Mutation struct {
}

type Query struct {
}

type Season struct {
	ID         string   `json:"id"`
	SeasonName *string  `json:"seasonName,omitempty"`
	Episodes   *Episode `json:"episodes"`
}

type SeasonInput struct {
	SeasonNumber int           `json:"seasonNumber"`
	Episodes     *EpisodeInput `json:"episodes"`
}

type SeriesFilter struct {
	Name *string `json:"name,omitempty"`
}

type SeriesInput struct {
	Title        string  `json:"Title"`
	Description  string  `json:"Description"`
	ReleaseDate  string  `json:"ReleaseDate"`
	EndDate      string  `json:"EndDate"`
	SeasonCount  int     `json:"SeasonCount"`
	EpisodeCount int     `json:"EpisodeCount"`
	Status       string  `json:"Status"`
	Rating       float64 `json:"Rating"`
	Creators     string  `json:"Creators"`
	Cast         string  `json:"Cast"`
}
